### ISSUE TITLE
Angularjs directive: connected support

### ISSUE THREAD

**Issue by bsr203** [voidberg/html5sortable#1]
Thank you for maintaining the plugin, and the angular directive.
I was trying to make it work for the connected example, but not sure it is supported.
Can you please help with this question at SO, or treat this as a feature request

http://stackoverflow.com/questions/18836939/angularjs-directive-html5-dragable-list

thanks
bsr.

**Comment by voidberg** [comment]
I'll take a look at it.

**Comment by bsr203** [comment]
@voidberg thanks for the quick response. I didn't set `ng-model` in the second example. Still, I am not sure how to maintain 2 models and somehow link them to enable drag-drop behavior.

**Comment by voidberg** [comment]
No problem.

Connecting them is easy (see here http://plnkr.co/edit/k1Qxpz?p=preview ) however I'm not sure at first glance how I can check if the item is coming from another model or not. Will continue to dig.

**Comment by bsr203** [comment]
Thanks. I too could make the connect work without any modification. I think to maintain the integrity of the data, it has to be in one model (2 dimensional array) or maintain a unique id as part of the data. 

In the sortupdate callback, what is the best way to get the `id` in our example. I am not an expert in jQuery, but saw  data.item points to the html element. May be that is one way to identify the element.

**Comment by voidberg** [comment]
I think I got it working. I'm not sure if it's the best way since I'm still learning Angular but you can find a version that works here: http://plnkr.co/edit/k1Qxpz?p=preview

I'll upload the changes to the repo too soon.

**Comment by voidberg** [comment]
A more cleaned version is now available in the repository along with some AngularJS examples.
