### ISSUE TITLE
sortupdate event fires when d&d position hasn't changed.

### ISSUE THREAD

**Issue by nevf** [voidberg/html5sortable#14]
The sortupdate READ.me info: 

```
This event is triggered when the user stopped sorting and _the DOM position has changed_.
```

I'm seeing the event fire when the drag pos == drop pos;  ui.item.index() == ui.oldindex. ie. The position hasn't changed. startparent & endparent are the same element. 

This seems odd and at present I can't work out why.

**Comment by voidberg** [comment]
Fixed.
