### ISSUE TITLE
Options are not used after destroying the sortable

### ISSUE THREAD

**Issue by eskimoblood** [voidberg/html5sortable#16]
When I call `sortable('destroy')`, the string `destroy` is stored in the data attribute of the element, when I try to initialize the element afterwards the passed options object is not used cause of this lines:

```
 var soptions = $(this).data('opts');

      if (typeof soptions == 'undefined') {
        $(this).data('opts', options);
      }
      else {
        options = soptions;
      }
```

The main failure is, that the passed strings are stored in the `data-opts`, it would also be better to always use the passed options instead of the one in the data attribute. Maybe a simple type check before storing the options would fix it. At the moment I clear the data attribute by myself, but it feels like a hack.

**Comment by voidberg** [comment]
Fixed.
