### ISSUE TITLE
Getting this to work with tables

### ISSUE THREAD

**Issue by TheSisb** [voidberg/html5sortable#2]
I want to be able to reorder rows in a normal table:

```
<table>
  <tbody>
    <tr>...</tr>
    <tr>...</tr>
    <tr>...</tr>
  </tbody>
</table>
```

The way this tests though is for ul/ol -> li else div.  Need to make it a bit smarter so it works for TRs.  Unless there's some limitation I'm missing?

**Comment by voidberg** [comment]
Will take a look.

**Comment by dmke** [comment]
> The way this tests though is for ul/ol -> li else div

Uhm... [this pull request](/farhadi/html5sortable/pull/33) pull request has [already been merged](/voidberg/html5sortable/blob/master/jquery.sortable.js#L45-L47):

``` javascript
var placeholder = ( options.placeholder == null )
  ? $('<' + (/^ul|ol$/i.test(this.tagName) ? 'li' : 'div') + ' class="sortable-placeholder">')
  : $( options.placeholder ).addClass('sortable-placeholder');
```

which allows to

> Use placeholder option to specify the markup of the placeholder:
> 
> ``` javascript
> $('.sortable').sortable({  
>   items: 'tr' ,
>   placeholder : '<tr><td colspan="7">&nbsp;</td></tr>'
> });
> ```

as documented [here](https://github.com/voidberg/html5sortable/blob/master/README.md) :-)

**Comment by voidberg** [comment]
dmke is correct, did not realize that. :)

Closing this issue.

**Comment by samnang** [comment]
@voidberg @dmke I'm not sure why when I drag it doesn't display preview the item that I am dragging along with my cursor.

![sortable table](https://cloud.githubusercontent.com/assets/131172/4213141/8b3f9bf8-38af-11e4-917a-30888f06a002.gif)

Unlike in your example, it displays it:

![sortable ul](https://cloud.githubusercontent.com/assets/131172/4213164/ef9d0e82-38af-11e4-9991-242df753fd5a.gif)

**Comment by lukasoppermann** [comment]
@samnang this is the "normal" behaviour when using handles. It is however a bug so I opened an issue https://github.com/voidberg/html5sortable/issues/75
