### ISSUE TITLE
Add this project to CDNJS?

### ISSUE THREAD

**Issue by scottbuckley** [voidberg/html5sortable#21]
I have been looking into having this project added to cdnjs.com.
The process of adding a project into cdnjs involves forking the actual cdnjs repo (https://github.com/cdnjs/cdnjs), adding your files where appropriate, and creating a pull request with your changes. 

The root version of html5sortable definitely meets the library popularity requirements for being added to cdnjs, and this fork almost does. Given that this is one of the most popular and best maintained forks of the original project, I think the cdnjs people would be happy to include this library on their cdn,

I can create the fork and pull request if you like, but I think as the author it might be more appropriate for you to do so. Let me know if you would like me to make the request for you.

**Comment by voidberg** [comment]
Hi Scott, 

Feel free to create the fork. :)

Thanks,
Andu

**Comment by scottbuckley** [comment]
Done. Applied for this to be added to CDNJS. I'll let you know how it goes.

**Comment by voidberg** [comment]
Thanks.

**Comment by scottbuckley** [comment]
Hi @voidberg. It's done! Your version of html5sortable now exists on CDNJS.

http://cdnjs.com/libraries/html5sortable

https://github.com/cdnjs/cdnjs/pull/3204
