### ISSUE TITLE
Parent styling class? 

### ISSUE THREAD

**Issue by ghost** [voidberg/html5sortable#28]
Hi I am interested to apply a class to the droppable list when dragging is in effect. Something similar to highlighting the background of the list when dragging is in motion depending on where the drag is currently at. This might be a good UX indication of the drag in progress. 

Will you consider adding a dragging-in-progress-item-is-on-top-of-this-container-class ?

**Comment by voidberg** [comment]
I think you can do this without any changes to the html.sortable code, I did it a while ago in a project. Will try to set up a plunker to demonstrate this.

**Comment by voidberg** [comment]
Here's an example on how you can do it: http://htmlpreview.github.io/?https://github.com/voidberg/html5sortable/blob/master/examples/angular-connected.html
