### ISSUE TITLE
multi-drag/drop?

### ISSUE THREAD

**Issue by seiyria** [voidberg/html5sortable#31]
Hi,

So I've been looking for a good alternative to jquery ui sortable and I happened upon this after a while. I'm trying to find a drag & drop library that supports multi-selection via shift and ctrl, as well as dropping them into the destination connected list. Is this possible?

Thanks!

**Comment by voidberg** [comment]
It's not possible at the moment and I don't have the time to try to implement this. Maybe someone else wants to give it a shot.
