### ISSUE TITLE
Remove version from dist filenames

### ISSUE THREAD

**Issue by xrstf** [voidberg/html5sortable#34]
I am in the process of integrating html5sortable into my application and for that I want to concat my vendor libraries (simply to save time to not re-compile my vendor libs all the time).

Unfortunately, to make my gruntfile stable, I would have to determine html5sortable's version first, so I can build the filename. And I don't want to nail my dependency inside the `bower.json` to a specific version.

I would welcome a change to not include the version number in the dist files (or having both versions).

**Comment by hergaiety** [comment]
Each release the bower.json is updated with the latest dist js file pointed to. If you're relying on exact filenames/locations in your concatenation you may want to automate such a process in your gruntfile with something like [main-bower-files](https://github.com/ck86/main-bower-files).

**Comment by voidberg** [comment]
I use the bower-install grunt plugin to avoid issues like this with other packages however it's probably a good idea to remove the version number from the dist files to make it easier for everyone. I'll leave this open for now as I am travelling for a couple of days and I'll fix it when I get back.

**Comment by voidberg** [comment]
Removed the version.
