### ISSUE TITLE
[Build] Add Source Maps to Build

### ISSUE THREAD

**Issue by coreyfarrell** [voidberg/html5sortable#36]
It would be very nice if javascript source maps were included in dist for each minified JS file.  Apparently this is now supported by uglifier:

https://github.com/gruntjs/grunt-contrib-uglify#new-options

**Comment by voidberg** [comment]
Good idea, thanks. Added to the dist folder.

**Comment by coreyfarrell** [comment]
The source map's have an incorrect sources property: "sources":["../src/html.sortable.js"]

The "../src/" part will prevent browsers from loading the original source.
