### ISSUE TITLE
AngularJS 1.2 compatibility

### ISSUE THREAD

**Issue by BinaryBrain** [voidberg/html5sortable#40]
Hi,
I just found that drag'n'dropping elements between two connected, ng-repeat lists, using AngularJS 1.2.\* would make some elements disapear.
However, they are present in the controller but not in the DOM.

Hope it helps!

**Comment by voidberg** [comment]
Closing this as it's a duplicate of #53 .

**Comment by BinaryBrain** [comment]
#53 is a duplicate of #40.
Whatever, thanks for the fix!
