### ISSUE TITLE
Making an easier way to get the current sort list at any given moment

### ISSUE THREAD

**Issue by sahanDissanayake** [voidberg/html5sortable#51]
Hi @voidberg 

In jquery UI you can get the sort list in array format using ....sortable("serialize") function;

It would be awesome to have that kinda functionality for html5sortable too.

Let me know if I could help. Cheers.

**Comment by philsbury** [comment]
@sahanDissanayake was this closed as it can be done? If so would you mind sharing how as I'm struggling with exactly this.

Cheers

**Comment by sahanDissanayake** [comment]
The way I did it was this

@philsbury http://jsfiddle.net/7qe14c9x/3/

**Comment by philsbury** [comment]
@sahanDissanayake nice, thank you!

**Comment by sahanDissanayake** [comment]
glad could help. Do you think this should be included in the plugin ?

@voidberg

**Comment by philsbury** [comment]
I'm dynamically adding items to it so it would certainly help in that context to get the items prior to any sorting.
