### ISSUE TITLE
html5sortable stop working in Firefox nightly

### ISSUE THREAD

**Issue by KingYes** [voidberg/html5sortable#54]
It's just stop working.
Do you know what I need to do for this?

**Comment by voidberg** [comment]
Confirmed, will look into this.

**Comment by KingYes** [comment]
Maybe it's problem with Firefox? You can see you can't drag any text from this version.. But if it's Firefox problem, we need to report about this bug.

**Comment by matthewsot** [comment]
It seems to be a problem with e10s, going into options -> unchecking "enable e10s" fixes the issue for me.

**Comment by KingYes** [comment]
Okay. Can you report this bug to e10s leader please?

**Comment by matthewsot** [comment]
Actually after searching through Bugzilla, looks to be an already known & fairly actively worked on bug - https://bugzilla.mozilla.org/show_bug.cgi?id=936092

**Comment by KingYes** [comment]
Cool. So I think we can close this issue for now.
