### ISSUE TITLE
Nested sorting?

### ISSUE THREAD

**Issue by dhardtke** [voidberg/html5sortable#55]
Hey,
I have a very weird issue: http://jsfiddle.net/v3b16mrq/

I would like to be able to sort the Subitems individually, and the upper li's too..

Is that possible?

Thanks in advance - any help is appreciated!

**Comment by tucker** [comment]
Hm, it just works.

Take a look here: http://codepen.io/anon/pen/pvJrKg

You can't use jsFiddle with github raw scripts. And I changed your classes a litttle bit.
I connected the child lists as well. Just remove the connectWith option if that is not wanted.

**Comment by dhardtke** [comment]
Thank you. It is working now for me
